#!/bin/bash
project=""
absolute=true
dir=""
error1="Inserisci come parametro il nome del progetto github da scaricare."
error2="Usa il flag -a per indicare un url completo, altrimenti si richiede solo il nome del progetto nel repository github/RedPanda243."

shopt -s extglob

if [ $# -eq 0 ]
then
    echo $error1
    echo $error2
else
  	if [ "$1" == "-a" ]
  	then
  		if [ -z "$2" ]
        then
  			echo $error1
        	echo $error2
  		else
  			project=$2
  		fi
  	else
  		if [ -z "$2" ]
  		then
  			project=https://github.com/RedPanda243/$1
  			absolute=false
  		else
  			if [ "$2" == "-a" ]
  			then
  				project=$1
  			else
  				echo $error1
        		echo $error2
  			fi
  		fi  		
  	fi
fi
dir=$(echo $project | cut -d'/' -f 5)
input="./$dir/dependencies"
git clone $project
while IFS= read -r line
do
  ./pull -a "$line"
done < "$input"